name: Lint and Format

on:
  workflow_dispatch:  
#  pull_request:
#  push:
#    branches-ignore:
#      - main


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  wpiformat:
   name: "wpiformat"
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Fetch all history and metadata
       run: |
         git fetch --prune --unshallow
         git checkout -b pr
         git branch -f main origin/main
     - name: Set up Python 3.8
       uses: actions/setup-python@v4
       with:
         python-version: 3.8
     - name: Install clang-format
       run: |
         wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
         sudo sh -c "echo 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-14 main' >> /etc/apt/sources.list.d/proposed-repositories.list"
         sudo apt-get update -q
         sudo apt-get install -y clang-format-14
     - name: Install wpiformat
       run: pip3 install wpiformat
     - name: Run
       run: wpiformat -clang 14
     - name: Check Output
       run: git --no-pager diff --exit-code HEAD
