name: reviewdog
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          checkstyle_config: sun_checks.xml
